# Generated by Django 3.1.7 on 2021-03-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(max_length=7)),
                ('cantidad', models.IntegerField(max_length=6)),
                ('unidad_medida', models.CharField(choices=[('PI', 'PI'), ('GLN', 'GLN'), ('CJ', 'CJ'), ('CUB', 'CUB'), ('TR', 'TR'), ('KG', 'KG'), ('KIT', 'KIT'), ('L', 'L'), ('M', 'M'), ('PAA', 'PAA'), ('ROL', 'ROL'), ('T', 'T'), ('TOT', 'TOT')], default=None, max_length=3)),
                ('clase_valoracion', models.CharField(choices=[('FABRICADO', 'FABRICADO'), ('REPARADO', 'REPARADO'), ('LINEA CONS', 'LINEA CONS'), ('LINEA PROP', 'LINEA PROP'), ('RECUPERADO', 'RECUPERADO'), ('INV CAP', 'INV CAP'), ('DAÑADO', 'DAÑADO'), ('CAP SPARE', 'CAP SPARE'), ('CALIBRADO', 'CALIBRADO')], default=None, max_length=10)),
                ('descripcion', models.CharField(max_length=40)),
                ('ubicacion', models.CharField(max_length=10)),
                ('almacen', models.CharField(choices=[(1001, 'Santa Catarina'), (1002, 'Garcia'), (1003, 'Aerospace'), (1004, 'Forja Abierta'), (1005, 'Aceria'), (1006, 'Precision')], default=None, max_length=4)),
                ('modelo', models.CharField(default=False, max_length=50)),
                ('marca', models.CharField(default=False, max_length=50)),
            ],
        ),
    ]
