# Generated by Django 3.1.7 on 2021-03-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_auto_20210305_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloinventario',
            name='marca',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='modeloinventario',
            name='modelo',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
