# Generated by Django 3.1.7 on 2021-03-13 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_auto_20210305_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloinventario',
            name='almacen',
            field=models.CharField(choices=[('Santa Catarina', 1001), ('Garcia', 1002), ('Aerospace', 1003), ('Forja Abierta', 1004), ('Aceria', 1005), ('Precision', 1006)], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='modeloinventario',
            name='clase_valoracion',
            field=models.CharField(choices=[('FABRICADO', 'FABRICADO'), ('REPARADO', 'REPARADO'), ('LINEA CONS', 'LINEA CONS'), ('LINEA PROP', 'LINEA PROP'), ('RECUPERADO', 'RECUPERADO'), ('INV CAP', 'INV CAP'), ('DAÑADO', 'DAÑADO'), ('CAP SPARE', 'CAP SPARE'), ('CALIBRADO', 'CALIBRADO')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='modeloinventario',
            name='codigo',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='modeloinventario',
            name='unidad_medida',
            field=models.CharField(choices=[('PI', 'PI'), ('GLN', 'GLN'), ('CJ', 'CJ'), ('CUB', 'CUB'), ('TR', 'TR'), ('KG', 'KG'), ('KIT', 'KIT'), ('L', 'L'), ('M', 'M'), ('PAA', 'PAA'), ('ROL', 'ROL'), ('T', 'T'), ('TOT', 'TOT')], default=None, max_length=20),
        ),
    ]
